######################################################################################
#                                                                                    #
# This is an intermediate file generated by the command ShallowFoundationGen.        #
# Source it after the ShallowFoundationGen command.                                  #
# Use this file to check shallow foundation nodes, elements,  fixity details         #
# ShallowFoundationGen.cpp is developed by Prishati Raychowdhury (UCSD)              #
#                                                                                    #
######################################################################################


 # Foundation Tag =1
 # Foundation Base Condition Tag =5

 #node   $NodeTag  $Xcoord  $Ycoord 
 node  1001  [expr -393.7+360] 0
 node  100001 [expr -393.7+360] 0
 node  1002  [expr -385.826+360] 0
 node  100002 [expr -385.826+360] 0
 node  1003  [expr -377.952+360] 0
 node  100003 [expr -377.952+360] 0
 node  1004  [expr -370.078+360] 0
 node  100004 [expr -370.078+360] 0

 node  1005  0 0
 node  100005 0 0

 node  1006  [expr -354.33+360] 0
 node  100006 [expr -354.33+360] 0
 node  1007  [expr -346.456+360] 0
 node  100007 [expr -346.456+360] 0
 node  1008  [expr -338.582+360] 0
 node  100008 [expr -338.582+360] 0
 node  1009  [expr -330.708+360] 0
 node  100009 [expr -330.708+360] 0
 node  1010  [expr -322.834+360] 0
 node  100010 [expr -322.834+360] 0
 node  1011  [expr -314.96+360] 0
 node  100011 [expr -314.96+360] 0
 node  1012  [expr -307.086+360] 0
 node  100012 [expr -307.086+360] 0


 node  1013  [expr -299.212+360] 0
 node  100013 [expr -299.212+360] 0
 node  1014  [expr -283.464+360] 0
 node  100014 [expr -283.464+360] 0
 node  1015  [expr -267.716+360] 0
 node  100015 [expr -267.716+360] 0
 node  1016  [expr -251.968+360] 0
 node  100016 [expr -251.968+360] 0
 node  1017  [expr -236.22+360] 0
 node  100017 [expr -236.22+360] 0
 node  1018  [expr -220.472+360] 0
 node  100018 [expr -220.472+360] 0
 node  1019  [expr -204.724+360] 0
 node  100019 [expr -204.724+360] 0
 node  1020  [expr -188.976+360] 0
 node  100020 [expr -188.976+360] 0
 node  1021  [expr -173.228+360] 0
 node  100021 [expr -173.228+360] 0
 node  1022  [expr -157.48+360] 0
 node  100022 [expr -157.48+360] 0
 node  1023  [expr -141.732+360] 0
 node  100023 [expr -141.732+360] 0
 node  1024  [expr -125.984+360] 0
 node  100024 [expr -125.984+360] 0
 node  1025  [expr -110.236+360] 0
 node  100025 [expr -110.236+360] 0
 node  1026  [expr -94.4881+360] 0
 node  100026 [expr -94.4881+360] 0
 node  1027  [expr -78.7401+360] 0
 node  100027 [expr -78.7401+360] 0
 node  1028  [expr -62.9921+360] 0
 node  100028 [expr -62.9921+360] 0
 node  1029  [expr -47.2441+360] 0
 node  100029 [expr -47.2441+360] 0
 node  1030  [expr -31.496+360] 0
 node  100030 [expr -31.496+360] 0
 node  1031  [expr -15.748+360] 0
 node  100031 [expr -15.748+360] 0
 node  1032  [expr 0+360] 0
 node  100032 [expr 0+360] 0
 node  1033  [expr 15.748+360] 0
 node  100033 [expr 15.748+360] 0
 node  1034  [expr 31.496+360] 0
 node  100034 [expr 31.496+360] 0
 node  1035  [expr 47.2441+360] 0
 node  100035 [expr 47.2441+360] 0
 node  1036  [expr 62.9921+360] 0
 node  100036 [expr 62.9921+360] 0
 node  1037  [expr 78.7401+360] 0
 node  100037 [expr 78.7401+360] 0
 node  1038  [expr 94.4881+360] 0
 node  100038 [expr 94.4881+360] 0
 node  1039  [expr 110.236+360] 0
 node  100039 [expr 110.236+360] 0
 node  1040  [expr 125.984+360] 0
 node  100040 [expr 125.984+360] 0
 node  1041  [expr 141.732+360] 0
 node  100041 [expr 141.732+360] 0
 node  1042  [expr 157.48+360] 0
 node  100042 [expr 157.48+360] 0
 node  1043  [expr 173.228+360] 0
 node  100043 [expr 173.228+360] 0
 node  1044  [expr 188.976+360] 0
 node  100044 [expr 188.976+360] 0
 node  1045  [expr 204.724+360] 0
 node  100045 [expr 204.724+360] 0
 node  1046  [expr 220.472+360] 0
 node  100046 [expr 220.472+360] 0
 node  1047  [expr 236.22+360] 0
 node  100047 [expr 236.22+360] 0
 node  1048  [expr 251.968+360] 0
 node  100048 [expr 251.968+360] 0
 node  1049  [expr 267.716+360] 0
 node  100049 [expr 267.716+360] 0
 node  1050  [expr 283.464+360] 0
 node  100050 [expr 283.464+360] 0
 node  1051  [expr 299.212+360] 0
 node  100051 [expr 299.212+360] 0


 node  1052  [expr 307.086+360] 0
 node  100052 [expr 307.086+360] 0
 node  1053  [expr 314.96+360] 0
 node  100053 [expr 314.96+360] 0
 node  1054  [expr 322.834+360] 0
 node  100054 [expr 322.834+360] 0
 node  1055  [expr 330.708+360] 0
 node  100055 [expr 330.708+360] 0
 node  1056  [expr 338.582+360] 0
 node  100056 [expr 338.582+360] 0
 node  1057  [expr 346.456+360] 0
 node  100057 [expr 346.456+360] 0
 node  1058  [expr 354.33+360] 0
 node  100058 [expr 354.33+360] 0

 node  1059  [expr 360+360] 0
 node  100059 [expr 360+360] 0

 node  1060  [expr 370.078+360] 0
 node  100060 [expr 370.078+360] 0
 node  1061  [expr 377.952+360] 0
 node  100061 [expr 377.952+360] 0
 node  1062  [expr 385.826+360] 0
 node  100062 [expr 385.826+360] 0
 node  1063  [expr 393.7+360] 0
 node  100063 [expr 393.7+360] 0
 node  100064 [expr 393.7+360] 0
 node  100065 [expr 393.7+360] 0

 #equalDOF $rNodeTag $cNodeTag $dof1 $dof2 $dof3
 equalDOF 12  1032 1 2 3 
equalDOF 11  1005 1 2 3
equalDOF 13  1059 1 2 3

 #Materials for shallow foundation

 #uniaxialMaterial  QzSimple2  $matTag  $SoilType  $Qult-end-extreme  $z50-end  <TpSoil>  <CradSoil> 
 uniaxialMaterial  QzSimple2 101  2 247.382 1.5386 2.67747e-316 1.14895e-315

 #uniaxialMaterial  QzSimple2  $matTag  $SoilType  $Qult-end  $z50-end  <TpSoil>  <CradSoil> 
 uniaxialMaterial  QzSimple2 102  2 494.763 1.5386 2.67747e-316 1.14895e-315

 #uniaxialMaterial  QzSimple2  $matTag  $SoilType  $Qult-mid  $z50-mid  <TpSoil>  <CradSoil> 
 uniaxialMaterial  QzSimple2 103  2 989.526 3.84651 2.67747e-316 1.14895e-315

 #uniaxialMaterial  PySimple2  $matTag  $SoilType  $Pp  $xp50  Cd  <CradSoil> 
 uniaxialMaterial  PySimple2 105  2 100.352 0.00187946 0.1 1.14895e-315

 #uniaxialMaterial  TzSimple2  $matTag  $SoilType  $Tult  $xt50  <CradSoil> 
 uniaxialMaterial  TzSimple2 106  2 505.135 0.0357 0.1 1.15057e-315

 #Vertical spring element connectivity
 #element   zeroLength  $eleTag  $iNode  $jNode  -mat$matTag  -dir  $dir 
 element   zeroLength 100001  100001  1001 -mat 101   -dir  2 
 element   zeroLength 100002  100002  1002 -mat 102   -dir  2 
 element   zeroLength 100003  100003  1003 -mat 102   -dir  2 
 element   zeroLength 100004  100004  1004 -mat 102   -dir  2 
 element   zeroLength 100005  100005  1005 -mat 102   -dir  2 
 element   zeroLength 100006  100006  1006 -mat 102   -dir  2 
 element   zeroLength 100007  100007  1007 -mat 102   -dir  2 
 element   zeroLength 100008  100008  1008 -mat 102   -dir  2 
 element   zeroLength 100009  100009  1009 -mat 102   -dir  2 
 element   zeroLength 100010  100010  1010 -mat 102   -dir  2 
 element   zeroLength 100011  100011  1011 -mat 102   -dir  2 
 element   zeroLength 100012  100012  1012 -mat 102   -dir  2 
 element   zeroLength 100013  100013  1013 -mat 103   -dir  2 
 element   zeroLength 100014  100014  1014 -mat 103   -dir  2 
 element   zeroLength 100015  100015  1015 -mat 103   -dir  2 
 element   zeroLength 100016  100016  1016 -mat 103   -dir  2 
 element   zeroLength 100017  100017  1017 -mat 103   -dir  2 
 element   zeroLength 100018  100018  1018 -mat 103   -dir  2 
 element   zeroLength 100019  100019  1019 -mat 103   -dir  2 
 element   zeroLength 100020  100020  1020 -mat 103   -dir  2 
 element   zeroLength 100021  100021  1021 -mat 103   -dir  2 
 element   zeroLength 100022  100022  1022 -mat 103   -dir  2 
 element   zeroLength 100023  100023  1023 -mat 103   -dir  2 
 element   zeroLength 100024  100024  1024 -mat 103   -dir  2 
 element   zeroLength 100025  100025  1025 -mat 103   -dir  2 
 element   zeroLength 100026  100026  1026 -mat 103   -dir  2 
 element   zeroLength 100027  100027  1027 -mat 103   -dir  2 
 element   zeroLength 100028  100028  1028 -mat 103   -dir  2 
 element   zeroLength 100029  100029  1029 -mat 103   -dir  2 
 element   zeroLength 100030  100030  1030 -mat 103   -dir  2 
 element   zeroLength 100031  100031  1031 -mat 103   -dir  2 
 element   zeroLength 100032  100032  1032 -mat 103   -dir  2 
 element   zeroLength 100033  100033  1033 -mat 103   -dir  2 
 element   zeroLength 100034  100034  1034 -mat 103   -dir  2 
 element   zeroLength 100035  100035  1035 -mat 103   -dir  2 
 element   zeroLength 100036  100036  1036 -mat 103   -dir  2 
 element   zeroLength 100037  100037  1037 -mat 103   -dir  2 
 element   zeroLength 100038  100038  1038 -mat 103   -dir  2 
 element   zeroLength 100039  100039  1039 -mat 103   -dir  2 
 element   zeroLength 100040  100040  1040 -mat 103   -dir  2 
 element   zeroLength 100041  100041  1041 -mat 103   -dir  2 
 element   zeroLength 100042  100042  1042 -mat 103   -dir  2 
 element   zeroLength 100043  100043  1043 -mat 103   -dir  2 
 element   zeroLength 100044  100044  1044 -mat 103   -dir  2 
 element   zeroLength 100045  100045  1045 -mat 103   -dir  2 
 element   zeroLength 100046  100046  1046 -mat 103   -dir  2 
 element   zeroLength 100047  100047  1047 -mat 103   -dir  2 
 element   zeroLength 100048  100048  1048 -mat 103   -dir  2 
 element   zeroLength 100049  100049  1049 -mat 103   -dir  2 
 element   zeroLength 100050  100050  1050 -mat 103   -dir  2 
 element   zeroLength 100051  100051  1051 -mat 103   -dir  2 
 element   zeroLength 100052  100052  1052 -mat 102   -dir  2 
 element   zeroLength 100053  100053  1053 -mat 102   -dir  2 
 element   zeroLength 100054  100054  1054 -mat 102   -dir  2 
 element   zeroLength 100055  100055  1055 -mat 102   -dir  2 
 element   zeroLength 100056  100056  1056 -mat 102   -dir  2 
 element   zeroLength 100057  100057  1057 -mat 102   -dir  2 
 element   zeroLength 100058  100058  1058 -mat 102   -dir  2 
 element   zeroLength 100059  100059  1059 -mat 102   -dir  2 
 element   zeroLength 100060  100060  1060 -mat 102   -dir  2 
 element   zeroLength 100061  100061  1061 -mat 102   -dir  2 
 element   zeroLength 100062  100062  1062 -mat 102   -dir  2 
 element   zeroLength 100063  100063  1063 -mat 101   -dir  2 

 #Horizontal spring element connectivity
 #element   zeroLength  $eleTag  $iNode  $jNode  -mat$matTag  -dir  $dir 
 element   zeroLength 100064  1063  100064 -mat 105   -dir  1 
 element   zeroLength 100065  1063  100065 -mat 106   -dir  1 

 # geomTransf Linear $transfTag <-jntOffset $dXi $dYi $dXj $dYj>
 geomTransf Linear  10

 #foundation element connectivity
 #element   elasticBeamColumn  $eleTag  $iNode  $jNode  $A  $E  $Iz  $transfTag 
 element elasticBeamColumn 1001 1001  1002 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1002 1002  1003 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1003 1003  1004 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1004 1004  1005 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1005 1005  1006 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1006 1006  1007 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1007 1007  1008 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1008 1008  1009 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1009 1009  1010 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1010 1010  1011 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1011 1011  1012 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1012 1012  1013 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1013 1013  1014 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1014 1014  1015 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1015 1015  1016 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1016 1016  1017 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1017 1017  1018 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1018 1018  1019 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1019 1019  1020 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1020 1020  1021 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1021 1021  1022 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1022 1022  1023 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1023 1023  1024 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1024 1024  1025 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1025 1025  1026 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1026 1026  1027 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1027 1027  1028 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1028 1028  1029 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1029 1029  1030 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1030 1030  1031 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1031 1031  1032 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1032 1032  1033 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1033 1033  1034 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1034 1034  1035 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1035 1035  1036 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1036 1036  1037 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1037 1037  1038 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1038 1038  1039 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1039 1039  1040 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1040 1040  1041 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1041 1041  1042 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1042 1042  1043 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1043 1043  1044 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1044 1044  1045 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1045 1045  1046 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1046 1046  1047 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1047 1047  1048 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1048 1048  1049 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1049 1049  1050 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1050 1050  1051 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1051 1051  1052 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1052 1052  1053 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1053 1053  1054 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1054 1054  1055 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1055 1055  1056 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1056 1056  1057 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1057 1057  1058 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1058 1058  1059 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1059 1059  1060 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1060 1060  1061 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1061 1061  1062 8524.98 3625.94 1.10114e+006 10
 element elasticBeamColumn 1062 1062  1063 8524.98 3625.94 1.10114e+006 10

 #fixity 
 fix  100001 1 1 1
 fix  100002 1 1 1
 fix  100003 1 1 1
 fix  100004 1 1 1
 fix  100005 1 1 1
 fix  100006 1 1 1
 fix  100007 1 1 1
 fix  100008 1 1 1
 fix  100009 1 1 1
 fix  100010 1 1 1
 fix  100011 1 1 1
 fix  100012 1 1 1
 fix  100013 1 1 1
 fix  100014 1 1 1
 fix  100015 1 1 1
 fix  100016 1 1 1
 fix  100017 1 1 1
 fix  100018 1 1 1
 fix  100019 1 1 1
 fix  100020 1 1 1
 fix  100021 1 1 1
 fix  100022 1 1 1
 fix  100023 1 1 1
 fix  100024 1 1 1
 fix  100025 1 1 1
 fix  100026 1 1 1
 fix  100027 1 1 1
 fix  100028 1 1 1
 fix  100029 1 1 1
 fix  100030 1 1 1
 fix  100031 1 1 1
 fix  100032 1 1 1
 fix  100033 1 1 1
 fix  100034 1 1 1
 fix  100035 1 1 1
 fix  100036 1 1 1
 fix  100037 1 1 1
 fix  100038 1 1 1
 fix  100039 1 1 1
 fix  100040 1 1 1
 fix  100041 1 1 1
 fix  100042 1 1 1
 fix  100043 1 1 1
 fix  100044 1 1 1
 fix  100045 1 1 1
 fix  100046 1 1 1
 fix  100047 1 1 1
 fix  100048 1 1 1
 fix  100049 1 1 1
 fix  100050 1 1 1
 fix  100051 1 1 1
 fix  100052 1 1 1
 fix  100053 1 1 1
 fix  100054 1 1 1
 fix  100055 1 1 1
 fix  100056 1 1 1
 fix  100057 1 1 1
 fix  100058 1 1 1
 fix  100059 1 1 1
 fix  100060 1 1 1
 fix  100061 1 1 1
 fix  100062 1 1 1
 fix  100063 1 1 1
 fix  100064 1 1 1
 fix  100065 1 1 1

 set endFootNodeL_1   1001
 set endFootNodeR_1   1063
 set endSprEleL_1   100001
 set endSprEleR_1   100063
 set midSprEle_1   100032
