######################################################################################
#                                                                                    #
# This is an intermediate file generated by the command ShallowFoundationGen.        #
# Source it after the ShallowFoundationGen command.                                  #
# Use this file to check shallow foundation nodes, elements,  fixity details         #
# ShallowFoundationGen.cpp is developed by Prishati Raychowdhury (UCSD)              #
#                                                                                    #
######################################################################################


 # Foundation Tag =1
 # Foundation Base Condition Tag =5

 #node   $NodeTag  $Xcoord  $Ycoord 
 node  1001  -33.4645 0
 node  100001 -33.4645 0
 node  1002  -32.7952 0
 node  100002 -32.7952 0
 node  1003  -32.1259 0
 node  100003 -32.1259 0
 node  1004  -31.4566 0
 node  100004 -31.4566 0
 node  1005  -30.7873 0
 node  100005 -30.7873 0
 node  1006  -30.1181 0
 node  100006 -30.1181 0
 node  1007  -29.4488 0
 node  100007 -29.4488 0
 node  1008  -28.7795 0
 node  100008 -28.7795 0
 node  1009  -28.1102 0
 node  100009 -28.1102 0
 node  1010  -27.4409 0
 node  100010 -27.4409 0
 node  1011  -26.7716 0
 node  100011 -26.7716 0
 node  1012  -26.1023 0
 node  100012 -26.1023 0
 node  1013  -25.433 0
 node  100013 -25.433 0
 node  1014  -24.0944 0
 node  100014 -24.0944 0
 node  1015  -22.7559 0
 node  100015 -22.7559 0
 node  1016  -21.4173 0
 node  100016 -21.4173 0
 node  1017  -20.0787 0
 node  100017 -20.0787 0
 node  1018  -18.7401 0
 node  100018 -18.7401 0
 node  1019  -17.4015 0
 node  100019 -17.4015 0
 node  1020  -16.063 0
 node  100020 -16.063 0
 node  1021  -14.7244 0
 node  100021 -14.7244 0
 node  1022  -13.3858 0
 node  100022 -13.3858 0
 node  1023  -12.0472 0
 node  100023 -12.0472 0
 node  1024  -10.7086 0
 node  100024 -10.7086 0
 node  1025  -9.37006 0
 node  100025 -9.37006 0
 node  1026  -8.03148 0
 node  100026 -8.03148 0
 node  1027  -6.6929 0
 node  100027 -6.6929 0
 node  1028  -5.35432 0
 node  100028 -5.35432 0
 node  1029  -4.01574 0
 node  100029 -4.01574 0
 node  1030  -2.67716 0
 node  100030 -2.67716 0
 node  1031  -1.33858 0
 node  100031 -1.33858 0
 node  1032  3.55271e-015 0
 node  100032 3.55271e-015 0
 node  1033  1.33858 0
 node  100033 1.33858 0
 node  1034  2.67716 0
 node  100034 2.67716 0
 node  1035  4.01574 0
 node  100035 4.01574 0
 node  1036  5.35432 0
 node  100036 5.35432 0
 node  1037  6.6929 0
 node  100037 6.6929 0
 node  1038  8.03148 0
 node  100038 8.03148 0
 node  1039  9.37006 0
 node  100039 9.37006 0
 node  1040  10.7086 0
 node  100040 10.7086 0
 node  1041  12.0472 0
 node  100041 12.0472 0
 node  1042  13.3858 0
 node  100042 13.3858 0
 node  1043  14.7244 0
 node  100043 14.7244 0
 node  1044  16.063 0
 node  100044 16.063 0
 node  1045  17.4015 0
 node  100045 17.4015 0
 node  1046  18.7401 0
 node  100046 18.7401 0
 node  1047  20.0787 0
 node  100047 20.0787 0
 node  1048  21.4173 0
 node  100048 21.4173 0
 node  1049  22.7559 0
 node  100049 22.7559 0
 node  1050  24.0944 0
 node  100050 24.0944 0
 node  1051  25.433 0
 node  100051 25.433 0
 node  1052  26.1023 0
 node  100052 26.1023 0
 node  1053  26.7716 0
 node  100053 26.7716 0
 node  1054  27.4409 0
 node  100054 27.4409 0
 node  1055  28.1102 0
 node  100055 28.1102 0
 node  1056  28.7795 0
 node  100056 28.7795 0
 node  1057  29.4488 0
 node  100057 29.4488 0
 node  1058  30.1181 0
 node  100058 30.1181 0
 node  1059  30.7873 0
 node  100059 30.7873 0
 node  1060  31.4566 0
 node  100060 31.4566 0
 node  1061  32.1259 0
 node  100061 32.1259 0
 node  1062  32.7952 0
 node  100062 32.7952 0
 node  1063  33.4645 0
 node  100063 33.4645 0
 node  100064 33.4645 0
 node  100065 33.4645 0

 #equalDOF $rNodeTag $cNodeTag $dof1 $dof2 $dof3
 equalDOF 11  1032 1 2 3 

 #Materials for shallow foundation

 #uniaxialMaterial  QzSimple2  $matTag  $SoilType  $Qult-end-extreme  $z50-end  <TpSoil>  <CradSoil> 
 uniaxialMaterial  QzSimple2 101  2 6.91884 0.224658 0.1 0.128

 #uniaxialMaterial  QzSimple2  $matTag  $SoilType  $Qult-end  $z50-end  <TpSoil>  <CradSoil> 
 uniaxialMaterial  QzSimple2 102  2 13.8377 0.224658 0.1 0.128

 #uniaxialMaterial  QzSimple2  $matTag  $SoilType  $Qult-mid  $z50-mid  <TpSoil>  <CradSoil> 
 uniaxialMaterial  QzSimple2 103  2 27.6754 1.12329 0.1 0.128

 #uniaxialMaterial  PySimple2  $matTag  $SoilType  $Pp  $xp50  Cd  <CradSoil> 
 uniaxialMaterial  PySimple2 105  2 30.1595 0.00623684 0.1 0.128

 #uniaxialMaterial  TzSimple2  $matTag  $SoilType  $Tult  $xt50  <CradSoil> 
 uniaxialMaterial  TzSimple2 106  2 80.695 0.0627 0.1 0.128

 #Vertical spring element connectivity
 #element   zeroLength  $eleTag  $iNode  $jNode  -mat$matTag  -dir  $dir 
 element   zeroLength 100001  100001  1001 -mat 101   -dir  2 
 element   zeroLength 100002  100002  1002 -mat 102   -dir  2 
 element   zeroLength 100003  100003  1003 -mat 102   -dir  2 
 element   zeroLength 100004  100004  1004 -mat 102   -dir  2 
 element   zeroLength 100005  100005  1005 -mat 102   -dir  2 
 element   zeroLength 100006  100006  1006 -mat 102   -dir  2 
 element   zeroLength 100007  100007  1007 -mat 102   -dir  2 
 element   zeroLength 100008  100008  1008 -mat 102   -dir  2 
 element   zeroLength 100009  100009  1009 -mat 102   -dir  2 
 element   zeroLength 100010  100010  1010 -mat 102   -dir  2 
 element   zeroLength 100011  100011  1011 -mat 102   -dir  2 
 element   zeroLength 100012  100012  1012 -mat 102   -dir  2 
 element   zeroLength 100013  100013  1013 -mat 103   -dir  2 
 element   zeroLength 100014  100014  1014 -mat 103   -dir  2 
 element   zeroLength 100015  100015  1015 -mat 103   -dir  2 
 element   zeroLength 100016  100016  1016 -mat 103   -dir  2 
 element   zeroLength 100017  100017  1017 -mat 103   -dir  2 
 element   zeroLength 100018  100018  1018 -mat 103   -dir  2 
 element   zeroLength 100019  100019  1019 -mat 103   -dir  2 
 element   zeroLength 100020  100020  1020 -mat 103   -dir  2 
 element   zeroLength 100021  100021  1021 -mat 103   -dir  2 
 element   zeroLength 100022  100022  1022 -mat 103   -dir  2 
 element   zeroLength 100023  100023  1023 -mat 103   -dir  2 
 element   zeroLength 100024  100024  1024 -mat 103   -dir  2 
 element   zeroLength 100025  100025  1025 -mat 103   -dir  2 
 element   zeroLength 100026  100026  1026 -mat 103   -dir  2 
 element   zeroLength 100027  100027  1027 -mat 103   -dir  2 
 element   zeroLength 100028  100028  1028 -mat 103   -dir  2 
 element   zeroLength 100029  100029  1029 -mat 103   -dir  2 
 element   zeroLength 100030  100030  1030 -mat 103   -dir  2 
 element   zeroLength 100031  100031  1031 -mat 103   -dir  2 
 element   zeroLength 100032  100032  1032 -mat 103   -dir  2 
 element   zeroLength 100033  100033  1033 -mat 103   -dir  2 
 element   zeroLength 100034  100034  1034 -mat 103   -dir  2 
 element   zeroLength 100035  100035  1035 -mat 103   -dir  2 
 element   zeroLength 100036  100036  1036 -mat 103   -dir  2 
 element   zeroLength 100037  100037  1037 -mat 103   -dir  2 
 element   zeroLength 100038  100038  1038 -mat 103   -dir  2 
 element   zeroLength 100039  100039  1039 -mat 103   -dir  2 
 element   zeroLength 100040  100040  1040 -mat 103   -dir  2 
 element   zeroLength 100041  100041  1041 -mat 103   -dir  2 
 element   zeroLength 100042  100042  1042 -mat 103   -dir  2 
 element   zeroLength 100043  100043  1043 -mat 103   -dir  2 
 element   zeroLength 100044  100044  1044 -mat 103   -dir  2 
 element   zeroLength 100045  100045  1045 -mat 103   -dir  2 
 element   zeroLength 100046  100046  1046 -mat 103   -dir  2 
 element   zeroLength 100047  100047  1047 -mat 103   -dir  2 
 element   zeroLength 100048  100048  1048 -mat 103   -dir  2 
 element   zeroLength 100049  100049  1049 -mat 103   -dir  2 
 element   zeroLength 100050  100050  1050 -mat 103   -dir  2 
 element   zeroLength 100051  100051  1051 -mat 103   -dir  2 
 element   zeroLength 100052  100052  1052 -mat 102   -dir  2 
 element   zeroLength 100053  100053  1053 -mat 102   -dir  2 
 element   zeroLength 100054  100054  1054 -mat 102   -dir  2 
 element   zeroLength 100055  100055  1055 -mat 102   -dir  2 
 element   zeroLength 100056  100056  1056 -mat 102   -dir  2 
 element   zeroLength 100057  100057  1057 -mat 102   -dir  2 
 element   zeroLength 100058  100058  1058 -mat 102   -dir  2 
 element   zeroLength 100059  100059  1059 -mat 102   -dir  2 
 element   zeroLength 100060  100060  1060 -mat 102   -dir  2 
 element   zeroLength 100061  100061  1061 -mat 102   -dir  2 
 element   zeroLength 100062  100062  1062 -mat 102   -dir  2 
 element   zeroLength 100063  100063  1063 -mat 101   -dir  2 

 #Horizontal spring element connectivity
 #element   zeroLength  $eleTag  $iNode  $jNode  -mat$matTag  -dir  $dir 
 element   zeroLength 100064  1063  100064 -mat 105   -dir  1 
 element   zeroLength 100065  1063  100065 -mat 106   -dir  1 

 # geomTransf Linear $transfTag <-jntOffset $dXi $dYi $dXj $dYj>
 geomTransf Linear  10

 #foundation element connectivity
 #element   elasticBeamColumn  $eleTag  $iNode  $jNode  $A  $E  $Iz  $transfTag 
 element elasticBeamColumn 1001 1001  1002 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1002 1002  1003 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1003 1003  1004 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1004 1004  1005 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1005 1005  1006 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1006 1006  1007 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1007 1007  1008 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1008 1008  1009 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1009 1009  1010 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1010 1010  1011 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1011 1011  1012 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1012 1012  1013 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1013 1013  1014 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1014 1014  1015 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1015 1015  1016 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1016 1016  1017 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1017 1017  1018 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1018 1018  1019 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1019 1019  1020 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1020 1020  1021 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1021 1021  1022 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1022 1022  1023 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1023 1023  1024 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1024 1024  1025 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1025 1025  1026 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1026 1026  1027 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1027 1027  1028 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1028 1028  1029 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1029 1029  1030 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1030 1030  1031 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1031 1031  1032 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1032 1032  1033 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1033 1033  1034 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1034 1034  1035 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1035 1035  1036 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1036 1036  1037 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1037 1037  1038 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1038 1038  1039 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1039 1039  1040 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1040 1040  1041 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1041 1041  1042 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1042 1042  1043 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1043 1043  1044 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1044 1044  1045 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1045 1045  1046 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1046 1046  1047 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1047 1047  1048 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1048 1048  1049 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1049 1049  1050 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1050 1050  1051 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1051 1051  1052 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1052 1052  1053 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1053 1053  1054 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1054 1054  1055 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1055 1055  1056 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1056 1056  1057 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1057 1057  1058 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1058 1058  1059 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1059 1059  1060 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1060 1060  1061 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1061 1061  1062 790.498 3625.94 9189.53 10
 element elasticBeamColumn 1062 1062  1063 790.498 3625.94 9189.53 10

 #fixity 
 fix  100001 1 1 1
 fix  100002 1 1 1
 fix  100003 1 1 1
 fix  100004 1 1 1
 fix  100005 1 1 1
 fix  100006 1 1 1
 fix  100007 1 1 1
 fix  100008 1 1 1
 fix  100009 1 1 1
 fix  100010 1 1 1
 fix  100011 1 1 1
 fix  100012 1 1 1
 fix  100013 1 1 1
 fix  100014 1 1 1
 fix  100015 1 1 1
 fix  100016 1 1 1
 fix  100017 1 1 1
 fix  100018 1 1 1
 fix  100019 1 1 1
 fix  100020 1 1 1
 fix  100021 1 1 1
 fix  100022 1 1 1
 fix  100023 1 1 1
 fix  100024 1 1 1
 fix  100025 1 1 1
 fix  100026 1 1 1
 fix  100027 1 1 1
 fix  100028 1 1 1
 fix  100029 1 1 1
 fix  100030 1 1 1
 fix  100031 1 1 1
 fix  100032 1 1 1
 fix  100033 1 1 1
 fix  100034 1 1 1
 fix  100035 1 1 1
 fix  100036 1 1 1
 fix  100037 1 1 1
 fix  100038 1 1 1
 fix  100039 1 1 1
 fix  100040 1 1 1
 fix  100041 1 1 1
 fix  100042 1 1 1
 fix  100043 1 1 1
 fix  100044 1 1 1
 fix  100045 1 1 1
 fix  100046 1 1 1
 fix  100047 1 1 1
 fix  100048 1 1 1
 fix  100049 1 1 1
 fix  100050 1 1 1
 fix  100051 1 1 1
 fix  100052 1 1 1
 fix  100053 1 1 1
 fix  100054 1 1 1
 fix  100055 1 1 1
 fix  100056 1 1 1
 fix  100057 1 1 1
 fix  100058 1 1 1
 fix  100059 1 1 1
 fix  100060 1 1 1
 fix  100061 1 1 1
 fix  100062 1 1 1
 fix  100063 1 1 1
 fix  100064 1 1 1
 fix  100065 1 1 1

 set endFootNodeL_1   1001
 set endFootNodeR_1   1063
 set endSprEleL_1   100001
 set endSprEleR_1   100063
 set midSprEle_1   100032
