K = importdata('C:\Users\lakshd5\Dropbox\Preliminary Analysis paper\Earthquakes\Ground motion records\GMfiles_far_source.txt');
index = importdata('C:\Users\lakshd5\Documents\Tcl\bin\GmRecordNum1.txt');
%index = 1;
% Sa = importdata('C:\Users\lakshd5\Dropbox\Preliminary Analysis paper\Earthquakes\Ground motion records\PGA.txt');
% Sa = Sa(index);
% fid = fopen('C:\Tcl\bin\IM.txt','w');
% fprintf(fid,'%12.8f',Sa);
% fclose(fid);
K1 = importdata(strcat('C:\Users\lakshd5\Dropbox\Preliminary Analysis paper\Earthquakes\Ground motion records\Far field records\',K{index},'.txt'));
data = K1(2:max(size(K1)),1:5);
data(isnan(data)) = 0;
% temp = K1.textdata;
% temp = temp{4,1};
numGMPTS = K1(1,1);%str2double(temp(1:6));
%temp_num = strfind(temp,'0.');
dT = K1(1,2);%str2double(temp(temp_num:temp_num+6));
fid1 = fopen('C:\Users\lakshd5\Documents\Tcl\bin\dT1.txt','w');
fprintf(fid1,'%12.8f',dT);
fclose(fid1);
fid2 = fopen('C:\Users\lakshd5\Documents\Tcl\bin\numGMPTS1.txt','w');
fprintf(fid2,'%12.8f', numGMPTS);
fclose(fid2);
fid3 = fopen('C:\Users\lakshd5\Documents\Tcl\bin\present_record1.txt','wt');
fprintf(fid3,'%12.8f %12.8f %12.8f %12.8f %12.8f\n', data');
fclose(fid3);