K = importdata('C:\Users\lakshd5\Dropbox\Preliminary Analysis paper\Earthquakes\Ground motion records\GMfiles_far_source.txt');
index = importdata('C:\Users\lakshd5\Documents\Tcl\bin\GmRecordNum.txt');
Sa = importdata('C:\Users\lakshd5\Dropbox\Preliminary Analysis paper\Earthquakes\Ground motion records\Sa.txt');
Sa = Sa(index);
fid = fopen('C:\Users\lakshd5\Documents\Tcl\bin\IM.txt','w');
fprintf(fid,'%12.8f',Sa);
fclose(fid);
K1 = importdata(strcat('C:\Users\lakshd5\Dropbox\Preliminary Analysis paper\Earthquakes\Ground motion records\Far field records\FEMA P695\',K{index},'.txt'));
data = K1(2:max(size(K1)),1:5);
data(isnan(data)) = 0;
numGMPTS = K1(1,1);
dT = K1(1,2);
fid1 = fopen('C:\Users\lakshd5\Documents\Tcl\bin\dT.txt','w');
fprintf(fid1,'%12.8f',dT);
fclose(fid1);
fid2 = fopen('C:\Users\lakshd5\Documents\Tcl\bin\numGMPTS.txt','w');
fprintf(fid2,'%12.8f', numGMPTS);
fclose(fid2);
fid3 = fopen('C:\Users\lakshd5\Documents\Tcl\bin\present_record.txt','wt');
fprintf(fid3,'%12.8f %12.8f %12.8f %12.8f %12.8f\n', data');
fclose(fid3);